-- for store
CREATE USER   :"STORE_DB_USER"
WITH PASSWORD :'STORE_DB_PSWD';

CREATE SCHEMA IF NOT EXISTS store;
CREATE SCHEMA IF NOT EXISTS bank;

-- for bank
CREATE USER   :"BANK_DB_USER"
WITH PASSWORD :'BANK_DB_PSWD';

