CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY,
    balance INTEGER NOT NULL DEFAULT 0,
    uuid TEXT NOT NULL UNIQUE,
    phash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY,
    ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount INTEGER NOT NULL,
    user_id INTEGER NOT NULL REFERENCES accounts (id),

    FOREIGN KEY (user_id) REFERENCES accounts
);

