CREATE SCHEMA IF NOT EXISTS bank;

CREATE TABLE IF NOT EXISTS bank.accounts (
    id SERIAL PRIMARY KEY,
    balance INTEGER NOT NULL DEFAULT 0,
    uuid TEXT NOT NULL UNIQUE,
    phash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bank.transactions (
    id SERIAL PRIMARY KEY,
    ts TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount INTEGER NOT NULL,
    user_id INTEGER NOT NULL REFERENCES bank.accounts (id),

    FOREIGN KEY (user_id) REFERENCES bank.accounts
);
