#!/bin/bash
set -e
set -u

psql -v ON_ERROR_STOP=1 \
	--username "${POSTGRES_USER}" \
	--dbname "${POSTGRES_DB}" <<-EOSQL
-- for store service
CREATE USER "${STORE_DB_USER}"
WITH PASSWORD '${STORE_DB_PSWD}';

GRANT ALL PRIVILEGES
ON SCHEMA store
TO "${STORE_DB_USER}";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES
IN SCHEMA store
TO "${STORE_DB_USER}";

GRANT USAGE
ON ALL SEQUENCES
IN SCHEMA store
TO "${STORE_DB_USER}";

ALTER DEFAULT PRIVILEGES
IN SCHEMA store
GRANT ALL
ON TABLES
TO "${STORE_DB_USER}";

-- for bank service
CREATE USER "${BANK_DB_USER}"
WITH PASSWORD '${BANK_DB_PSWD}';

GRANT ALL PRIVILEGES
ON SCHEMA bank
TO "${BANK_DB_USER}";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES
IN SCHEMA bank
TO "${BANK_DB_USER}";

GRANT USAGE
ON ALL SEQUENCES
IN SCHEMA bank
TO "${BANK_DB_USER}";

ALTER DEFAULT PRIVILEGES
IN SCHEMA bank
GRANT ALL
ON TABLES
TO "${BANK_DB_USER}";

-- for all
REVOKE ALL
ON SCHEMA public
FROM public;

EOSQL

